### ISSUE TITLE
the axis orientation of orbslam2

### ISSUE THREAD

**Issue by yongguanjiangshan** [DRosemei/RoMe#12]
hello, There are camera poses in the sequences/orbslam2. Could you tell me the axis orientation of world coordinate?

**Comment by DRosemei** [comment]
@yongguanjiangshan Hi, you can refer to this [line](https://github.com/DRosemei/RoMe/blob/main/datasets/kitti.py#L133) which transfrom coordinate from [right, down, forward](camera coordinate) to [forward, left, up](chassis/word coordinate).

**Comment by yongguanjiangshan** [comment]
thank you for your quickly reply! the unit of world coordinate is m, is it?

**Comment by DRosemei** [comment]
@yongguanjiangshan  Yes，it is.
