### ISSUE TITLE
about `__opencv_camera2pytorch3d` in dataset/base.py

### ISSUE THREAD

**Issue by yanjh97** [DRosemei/RoMe#15]
Hi, thanks for your great work. 
I'm confused about [this line](https://github.com/DRosemei/RoMe/blob/main/datasets/base.py#L103), why does the rotation matrix need to be tranposed ?
I think it's already for world2camera, which is exactly the input parameter (after times -1 for x, y axis) of PerspectiveCameras in Pytorch3D.

**Comment by DRosemei** [comment]
@yanjh97 You can refer [here](https://github.com/facebookresearch/pytorch3d/blob/a3d99cab6bf5eb69be8d5eb48895da6edd859565/pytorch3d/renderer/camera_conversions.py#L46). We need to convert coordinate from opencv to pytorch3d.

**Comment by yanjh97** [comment]
@DRosemei I got it, thanks!
