### ISSUE TITLE
cannot overfit single image

### ISSUE THREAD

**Issue by lcc815** [DRosemei/RoMe#16]
thanks for your great work, which helps the community a lot.
But I cannot learn a very clear mesh texture, so I try to overfit single image, and the rendered image is always blurred. following images are gt image and rendered image.
![gt image](https://github.com/DRosemei/RoMe/assets/97278927/4fe23b8a-9947-4af1-9764-369fa627eec0)
![rendered image](https://github.com/DRosemei/RoMe/assets/97278927/faabcb52-bed5-47f4-94bd-bb3da02db937)

I didn't change any settings of the origin code. Could you please give me some hint to find the reason why this happen? Thanks so much for your help.

**Comment by lcc815** [comment]
I observed the loss. It cannot converge to zero no matter how many epochs it runs.

**Comment by DRosemei** [comment]
@lcc815 You can try to decrease bev_resolution (defalut is 0.1 meter) and enlarge bev range. Besides, if height or pose is not correct, it may be blurry.

**Comment by lcc815** [comment]
thanks for your quick reply. I will try it :)

**Comment by lcc815** [comment]
yes! You are right, bev_resolution matters and problem solved!
