### ISSUE TITLE
problems when using custom dataset

### ISSUE THREAD

**Issue by yongguanjiangshan** [DRosemei/RoMe#17]
hi, @DRosemei , thank you for your advances and patience. now i can use my custom dataset to generate bev_rgb and bev_seg. but now the blend image is bad. could you give me some suggestions to solve this? below are some result images.

bev_rgb:
![bev_rgb_20_1fc1cc6e05b61034d48b](https://github.com/DRosemei/RoMe/assets/18051804/e9e0c95b-13d2-414e-bb1a-6a4e9593e592)

bev_seg:
![bev_seg_20_b87ac3a2b3c37afe30fd](https://github.com/DRosemei/RoMe/assets/18051804/3dff6415-e2c1-478d-92ba-9dac830614a7)

blend_image:
![blend_image_20_0ede2b3197a6b42b08cf](https://github.com/DRosemei/RoMe/assets/18051804/53e72b2d-f5fe-4933-88ee-08af443bef1e)

gt_image:
![gt_image_20_efb25c6fe6f5163d1f55](https://github.com/DRosemei/RoMe/assets/18051804/accf19a7-6eaa-408c-8dfa-0925d49a2f0b)

render_gt_seg:
![render_gt_seg_20_04906dcb1e4cfa3c3a56](https://github.com/DRosemei/RoMe/assets/18051804/4a3f4ab3-5102-44ba-9d1d-7bda1d328357)

render_image:
![render_image_20_0cf65de6a996fb3c1876](https://github.com/DRosemei/RoMe/assets/18051804/98ef1ca2-7f99-4573-a05c-628acb0d8bb1)

render_mask:
![render_mask_20_5c3ad3468872285bc206](https://github.com/DRosemei/RoMe/assets/18051804/0010e6d9-becf-4d9e-9ff2-bde0a06cc1b8)

render_seg:
![render_seg_20_d7c7ae149935f8428c44](https://github.com/DRosemei/RoMe/assets/18051804/0d8e2fad-36a0-4996-888b-91f2067055df)

**Comment by DRosemei** [comment]
@yongguanjiangshan I find that your images have not been undistored and you can rectify them first.
![image](https://github.com/DRosemei/RoMe/assets/27892562/0678b3a4-31f1-465e-8f6f-cffab1ab1be8)

**Comment by yongguanjiangshan** [comment]
> @yongguanjiangshan I find that your images have not been undistored and you can rectify them first. ![image](https://user-images.githubusercontent.com/27892562/269270419-0678b3a4-31f1-465e-8f6f-cffab1ab1be8.png)

hi, DRosemei, i have rectify the image. my original image is a fisheye image. as show below. By the way, i use the rectify algorithm in our company to rectify the image instead of the undistort() function in opencv. is it the rectify algorithm problem?

original fisheye image:
![front_000056](https://github.com/DRosemei/RoMe/assets/18051804/1db6ae85-2112-4b12-a7a4-2dbbe63376ea)

**Comment by DRosemei** [comment]
@yongguanjiangshan You can check the rectify algorithm first. Objects in red boxes are not upright.
![image](https://github.com/DRosemei/RoMe/assets/27892562/2b8b96e5-a908-41d6-9c4e-4ab4415e4fa0)

**Comment by yongguanjiangshan** [comment]
> @yongguanjiangshan You can check the rectify algorithm first. 

thank you very much, i will check it.

**Comment by ycdhqzhiai** [comment]
@yongguanjiangshan How did you obtain the segmented image?
