### ISSUE TITLE
The question about set the bev_resolution

### ISSUE THREAD

**Issue by AnMoran** [DRosemei/RoMe#22]
when bev_resolution set 0.1，  the bev result is normal, but when set 0.05，the bev_rgb has white line
<img width="486" alt="image" src="https://github.com/DRosemei/RoMe/assets/33443619/46775865-9928-46d9-b0e9-48baa48f7afb">
<img width="592" alt="image" src="https://github.com/DRosemei/RoMe/assets/33443619/54685b77-4ac4-4124-90ef-ba341662623c">
the 0.1 result is normal
![image](https://github.com/DRosemei/RoMe/assets/33443619/d61ea1b1-c35f-4eb6-842f-90e8b036ffbc)
other dataset has same question!

**Comment by DRosemei** [comment]
Hi, this is because there are too many vertivces and try to decrease bev length or increase bev resolution. It is a problem in pytorch3D and try another mesh render tool may fix it.

**Comment by AnMoran** [comment]
ths
