### ISSUE TITLE
confused about the results of the road reconstruction 

### ISSUE THREAD

**Issue by zjtde1990** [DRosemei/RoMe#23]
I am confused about the results of the road reconstruction. The beginning looks good, but the end is really poor. And why is that? What caused  the error?
![屏幕截图 2023-10-26 110227](https://github.com/DRosemei/RoMe/assets/35866379/44342bd2-fb29-425c-acbd-202c7bd929ac)

**Comment by DRosemei** [comment]
@zjtde1990  Hi. It may be caused by many reasons, such as wrong camera poses, wrong bev elevation. It seems to be a slope and you can use other supervisions like lidar depth.

**Comment by zjtde1990** [comment]
I used kitti odometry gt poses, and reconstruct the sparse point clouds with colmap. Then I reconstruct the dense point clouds. I pre-trained the elevation mlp with the dense point clouds which is masked by semantic labels. I obtained the depth image by projecting dense point clouds to the image, and then I used the depth image as supervisions. I want to know if the problem is on the pre-training mlp or the depth of the dense point clouds are inaccurate.

**Comment by DRosemei** [comment]
@zjtde1990 At first dense point clouds obtained by MVS have many errors and you can see points on road are noisy. Second, when you project points, have you sorted depth by distance? It may cause error when distance points cover close points.

**Comment by zjtde1990** [comment]
@DRosemei Thank you very much~ I really ignored that the projection points would overlap. However, from my understanding, RoMe's reconstruction results are based on high-precision poses and point clouds inputs.  It mainly plays the role of smoothing and rebuilding semantics, and can not correct the pose and elevation to a certain extent. I don't know if I understand correctly.

**Comment by DRosemei** [comment]
@zjtde1990 Yes, high-precision poses and point clouds inputs will make less reprojection errors. For correcting the pose and elevation, only vision supervision is not enough in autonomous driving because light/exposure conditions may change heavily in a short clip. So RoMe could correct poses and elevation under good light/exposure conditions. In wild data, you need to get high-precision poses first which makes it easier to learn the elevation.
