### ISSUE TITLE
numpy size match error duing evaluation

### ISSUE THREAD

**Issue by LevinJ** [DRosemei/RoMe#26]
After enabling the eval feature (via eval: True) in local_nusc.yaml, evaluation relevant scripts will be executed at the end of the training, and below numpy size match error would occur at the `blend_image = cv2.addWeighted(gt_image, 0.5, vis_seg, 0.5, 0)` line.

![size_match](https://github.com/DRosemei/RoMe/assets/1629014/2fa7c8cc-c7ca-4ed9-a679-9924fd3eb075)

gt_image is of shape (4, 225,800,3), while vis_seg is of (225, 800,3)

**Comment by DRosemei** [comment]
@LevinJ I'm sorry that it only supports batch_size=1 for now and you can split it for 4 or more images evaluation in a iteration.
![image](https://github.com/DRosemei/RoMe/assets/27892562/6e204167-4bab-4d81-b230-027594932ee9)

**Comment by LevinJ** [comment]
@DRosemei , Thanks for your kind reply. Yes, I later also realized we could use the eval script to do the evaluation. Truly appreciate your generous act of opening sourcing this nice project, which is very helpful and inspiring for me. Great work!
