### ISSUE TITLE
Estimates of the height of protrusions (e.g. curbs, fences) on the road

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [DRosemei/RoMe#27]
hi, it seems that this is a focus on road reconstruction, but how to deal with the reconstruction of curbs and other raised landmarks in a purely visual scene。

**Comment by DRosemei** [comment]
@wangyuanbiubiubiu Hi, it is hard for RoMe to reconstruct raised landmarks and you can refer to other mesh reconstruction methods like [streetsurf](https://ventusff.github.io/streetsurf_web/).

**Comment by wangyuanbiubiubiu** [comment]
> @wangyuanbiubiubiu Hi, it is hard for RoMe to reconstruct raised landmarks and you can refer to other mesh reconstruction methods like [streetsurf](https://ventusff.github.io/streetsurf_web/).

I tried streetsurf and he didn't do well in the actual data; So I found your job, and if I add some height constraints to the ground where the height changes dramatically, would that be good?

**Comment by DRosemei** [comment]
We have tried on carla with dense depth supervision and you can see that curbs can be learned well but the pole only gets partial reconstruction. So you can give some strong supervision for these areas.
[carla_3d_mesh.zip](https://github.com/DRosemei/RoMe/files/13435464/carla_3d_mesh.zip)
![image](https://github.com/DRosemei/RoMe/assets/27892562/3ab65614-d20d-4823-a457-83527a10d629)

**Comment by wangyuanbiubiubiu** [comment]
> 我们在 Carla 上进行了密集深度监督的尝试，您可以看到路缘石可以很好地学习，但杆子只能得到部分重建。所以你可以对这些领域进行一些强有力的监督。 [Carla_3d_mesh.zip](https://github.com/DRosemei/RoMe/files/13435464/carla_3d_mesh.zip) ![图像](https://user-images.githubusercontent.com/27892562/284834247-3ab65614-d20d-4823-a457-83527a10d629.png)

Thanks, I'm now going to add some deph normal to RoMe to monitor this edge change
