### ISSUE TITLE
about the camera pose?

### ISSUE THREAD

**Issue by rockywind** [DRosemei/RoMe#3]
Hi, thank you for sharing the great work!
I am confused about the camera pose in KITTI odometry datasets. Specifically:

- camera2chassis is the rotation matrix representing the orientation of the camera frame relative to the IMU frame.

- The poses provided in the KITTI odometry dataset are transforms from world coordinates to camera coordinates.

- I'm unsure why the KITTI odometry poses need to be multiplied by camera2chassis to get the full transform from world to IMU.

My understanding is that the poses from KITTI already encode the full transformation from world to camera coordinates. Multiplying by an additional camera-to-IMU rotation seems redundant. The camera frame and IMU frame should share the same orientation in the world coordinate system based on how they are rigidly mounted on the vehicle.

Please let me know if I am missing something or have misunderstood how the coordinate systems are defined in KITTI. I would appreciate any clarification on why the extra camera2chassis rotation is required when using the KITTI odometry poses.
![image](https://github.com/DRosemei/RoMe/assets/14838781/18f3690a-748f-406b-8203-3c6644507e82)

**Comment by DRosemei** [comment]
@rockywind It maybe  little confusing. Chassis here I mean is chassis corrdinate,(x is forward, y is left and z is up), compared with camera corrdinate (x is right, y is down, z is forward). Here I just convert axis orientation. Thanks for pointing it out.

**Comment by rockywind** [comment]
Thanks a lot!
I  guess the camera pose before being multiplied by camera2chassis is  from camera coordinate to world coordinate.

**Comment by rockywind** [comment]
@DRosemei 您好，请教个问题哈！
1. 我理解camera pose是world to cam, camera2chassis是camera to IMU,两个相乘得到的camera pose是world to cam，但是3个轴是转成IMU的坐标系。不知我理解，对不对？
2. 下图的ref_camera2world是不是应该写成ref_world2camera, 因为ref_pose是从上面camera pose得来的
![image](https://github.com/DRosemei/RoMe/assets/14838781/ef070c3c-d078-41e0-9808-fbc74f4f0863)
