### ISSUE TITLE
Renderer may have truncation error

### ISSUE THREAD

**Issue by clmforgit** [DRosemei/RoMe#31]
hi, dear author,

Thanks for your excellent work!
I test the renderer, using the code like this:

```
 for i in range(5):
      cameras = PerspectiveCameras(
          R=R_pytorch3d,
          T=T_pytorch3d + torch.Tensor([0,0,i * 0.05]).type_as(T_pytorch3d),
          focal_length=focal_pytorch3d,
          principal_point=p0_pytorch3d,
          image_size=image_shape,
          device=device
      )
```
so the rendered result should move slightly. But actually, some images are exactly the same, which is not as expected.
My pytorch3d verson is   0.6.1. Can you reproduce this?

**Comment by DRosemei** [comment]
@clmforgit  Can you provide some gt images and render images?

**Comment by clmforgit** [comment]
> @clmforgit Can you provide some gt images and render images?
![eval_00000-blend](https://github.com/DRosemei/RoMe/assets/26374818/02300c5c-a8b2-41ce-9cc4-e652f9a7016b)
![eval_00001-blend](https://github.com/DRosemei/RoMe/assets/26374818/183cc9c5-23f1-4483-afc3-4fa964d3b746)
![eval_00002-blend](https://github.com/DRosemei/RoMe/assets/26374818/9bf7e052-6a4a-43d3-831b-ea783db4fe78)
![eval_00003-blend](https://github.com/DRosemei/RoMe/assets/26374818/2acae5e3-7771-4dad-bab5-af20555747a0)
![eval_00004-blend](https://github.com/DRosemei/RoMe/assets/26374818/38119307-5ea8-440d-b676-d29f23480558)

the 5 blend images are generated using eval.py from a grid model, by modifying code of cameras to get 5 rendered seg for 1 gt image. It can be seen that the 2nd 3rd 4th images are exactly the same.

**Comment by DRosemei** [comment]
@clmforgit The first and last image are not the same in details. Moving 5cm for each image makes little changes.
![image](https://github.com/DRosemei/RoMe/assets/27892562/ff6c649b-1f89-48bd-b20a-1bb049f9f8c2)
![image](https://github.com/DRosemei/RoMe/assets/27892562/608c105e-ea53-4db0-870c-901b49d0fb0b)

**Comment by DRosemei** [comment]
@clmforgit The key reason is that your bev resolution is set to 10cm, if you want to see more details, decrease the bev resolution.

**Comment by clmforgit** [comment]
Yes, that makes sense. I doubt if it is a bug or something in pytorch3d.
