### ISSUE TITLE
blurred and jagged reconstruction result when using custom data

### ISSUE THREAD

**Issue by LevinJ** [DRosemei/RoMe#33]
Applying Rome on custom data collected by ourselves, the road surface reconstruction looks abnormal. Just wonder what might be the possible reasons, and what potential steps I might follow to identify the root cause and fix the problems. Any tips/guidance are greatly appreciated, Thanks.

Below are the original undistorted raw image samples,

![rgb_00021](https://github.com/DRosemei/RoMe/assets/1629014/a71d40fb-a2bf-4faf-8482-54c7b7426d8b)

![rgb_00046](https://github.com/DRosemei/RoMe/assets/1629014/55ae4786-06e4-4979-b640-1fcbe8afb250)

![rgb_00078](https://github.com/DRosemei/RoMe/assets/1629014/fd596763-5c4c-4d69-b408-b094c125d385)

Below are the reconstruction results,

![bev_rgb_7_68e49e0e66c481d5489b](https://github.com/DRosemei/RoMe/assets/1629014/ab919a5e-b090-46ab-9ca0-e9e17a2d2724)

![bev_seg_7_038980f6984edae92c0e](https://github.com/DRosemei/RoMe/assets/1629014/6ca54f26-c6f2-4aaf-b60e-684676372659)

![blend_image_7_e95724d50a846184a5fa](https://github.com/DRosemei/RoMe/assets/1629014/b60f14d1-ff2d-492e-85e0-b42769f17c5f)

![render_image_7_512b8b6e28ec6a0d4105](https://github.com/DRosemei/RoMe/assets/1629014/778e39e9-6a41-49f3-aec1-343a089edfa6)

**Comment by DRosemei** [comment]
Sorry for late reply and there may be 3 reasons.
1. Most important one: poses accuracy.
2. Elevation estimation. You can check by comparing reconstructed points from traditional methods and your estimated road mesh.
3. Frame rate. If it is too low, it may cause such results below.
![image](https://github.com/DRosemei/RoMe/assets/27892562/d1352c41-121a-4449-9665-14e9736623a6)

**Comment by LevinJ** [comment]
Hi @DRosemei , Thanks a lot for the input.

1. I used the outoput from a novtel pbox with RTK to derive camera poses. will double check relevant codes.
2. The distance between subsequent frames are mostly less than 1 meter, though some of the subsequent frames have larger distance, like 8 meters, will look into the issue.

Regarding reconstructing the scene with traditional methods, Which open source tools would you recommend for this purpose?

**Comment by DRosemei** [comment]
@LevinJ We all use colmap to reconstruct scenes as you can see [here](https://arxiv.org/pdf/2309.11754.pdf).
![image](https://github.com/DRosemei/RoMe/assets/27892562/a3896e50-1f5b-48a8-afa0-4f729cbf5fe7)

**Comment by LevinJ** [comment]
Yes, I guessed it would be colmap. Thanks for your confirmation,  @DRosemei
