### ISSUE TITLE
Questions about the results of Mask2Former

### ISSUE THREAD

**Issue by runnerhdh** [DRosemei/RoMe#35]
Hi, thank you for your open source. I would like to ask you how to use Mask2Former to obtain fine-grained semantic segmentation results, such as each zebra crossing and each dotted line. I cannot get these fine-grained segmentation results using  Mask2Former. Thanks very much.

**Comment by DRosemei** [comment]
@runnerhdh Have you read this script [here](https://github.com/DRosemei/RoMe/blob/a634caa302a34d0631f4e81351a04ee612f9f654/scripts/mask2former_infer/infer.sh)? We all use this model and configs to parse semantic labels.

**Comment by runnerhdh** [comment]
Thank you for your reply!
Yes, i used the same configuration file and pre-trained model. Did you directly use the model to infer the following results (zebra crossing and dotted line pointed by the red arrow)? 
![Screenshot from 2024-01-22 13-04-08](https://github.com/DRosemei/RoMe/assets/43984723/1d97a18a-18b2-4557-b912-4eaf140c4917)
![Screenshot from 2024-01-22 13-03-39](https://github.com/DRosemei/RoMe/assets/43984723/e3c69e0d-089e-4780-b7c9-298b5cb45106)

My reasoning results are as follows: (original picture on the top, inference result on the bottom), the zebra crossing and dotted line are not separated according to instance.
![Screenshot from 2024-01-22 13-06-46](https://github.com/DRosemei/RoMe/assets/43984723/9d92634a-05b0-45f3-93d1-7373873df454)
![Screenshot from 2024-01-22 13-08-16](https://github.com/DRosemei/RoMe/assets/43984723/aa397793-1798-4f32-9d09-2234c780fbc6)
![1](https://github.com/DRosemei/RoMe/assets/43984723/6aa10bfc-e223-4ae2-8544-f1f619bfead1)
![2](https://github.com/DRosemei/RoMe/assets/43984723/19cf6123-820a-4bb2-9310-b53a77471ca3)

**Comment by DRosemei** [comment]
@runnerhdh I'm sorry that we use trained semantic model in our company which can not be released and you can search for other open source semantic models.

**Comment by runnerhdh** [comment]
ok, thanks~
