### ISSUE TITLE
Taking fisheye camera as input

### ISSUE THREAD

**Issue by superjuices** [DRosemei/RoMe#37]
Excellent work, I have a question: If the input image comes from a fisheye camera, in addition to undistorting the image as input, I want to use the fisheye image directly. Do you have any suggestions for doing this?

**Comment by DRosemei** [comment]
@superjuices You can refer [here](https://github.com/facebookresearch/pytorch3d/blob/1f92c4e9d25121326d77838035748fc7b71a5cfd/pytorch3d/renderer/fisheyecameras.py#L21) to use FishEyeCameras rendering.

**Comment by superjuices** [comment]
@DRosemei Thanks a lot，I will try it.  Also, I have a problem, a warning appears during training：
**"Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization."**，and how to solve it?

Finally, if I want to transfer it to some scenes where the viewing distance is not particularly large, how should the training parameters be adjusted?

Thank you ！！

**Comment by superjuices** [comment]
> @DRosemei Thanks a lot，I will try it. Also, I have a problem, a warning appears during training： **"Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization."**，and how to solve it?
> 
> Finally, if I want to transfer it to some scenes where the viewing distance is not particularly large, how should the training parameters be adjusted?
> 
> Thank you ！！

Just like this output, the ring road accounts for too few pixels in the entire image. How can I increase its proportion?
![Uploading 企业微信截图_20240206151316.png…]()

**Comment by DRosemei** [comment]
@superjuices Sorry for late reply. One solution is that spliting a single fisheye image to several pinhole images. May it help you.

**Comment by superjuices** [comment]
> @superjuices Sorry for late reply. One solution is that spliting a single fisheye image to several pinhole images. May it help you.

感谢你的恢复 ！！ ，再请教个问题，像是下图这样的重建结果，有很多条纹，这种原因通常是没有完全收敛的原因吗 
![test](https://github.com/DRosemei/RoMe/assets/92207812/7d23f0c2-3ee1-47a6-b33e-7cd9b006a783)

**Comment by DRosemei** [comment]
看起来是相邻帧间光照差很多，可以增大epoch数看下
