### ISSUE TITLE
After installing the specified version of the package and running an error message, can you provide a Docker?

### ISSUE THREAD

**Issue by lliuguangwei** [DRosemei/RoMe#38]
The installed package version is as follows:
torch                  1.10.2+cu111
torchaudio             0.10.2+cu111
torchvision            0.11.3+cu111
pytorch3d              0.6.1              /home/pytorch3d

Error:
  0%|                                                                                                                                                            | 0/7 [00:00<?, ?it/s]epoch-1: get 1 waypoints
+ 1139, num_frames = 1139
/home/pytorch3d/pytorch3d/structures/meshes.py:1108: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  self._edges_packed = torch.stack([u // V, u % V], dim=1)
  0%|                                                                                                                                                            | 0/7 [00:02<?, ?it/s]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/miniconda/envs/rome_1/lib/python3.8/site-packages/IPython/core/debugger.py", line 145, in BdbQuit_excepthook
    raise ValueError(
ValueError: `BdbQuit_excepthook` is deprecated since version 5.1

Original exception was:
Traceback (most recent call last):
  File "scripts/train.py", line 336, in <module>
    train(configs)
  File "scripts/train.py", line 121, in train
    poses = ExtrinsicModel(configs, optim_dict["rotations"], optim_dict["translations"], num_camera=len(dataset.camera_extrinsics)).to(device)
  File "/home/pytorch3d/pytorch3d/loss/mesh_laplacian_smoothing.py", line 123, in mesh_laplacian_smoothing
    loss = L.mm(verts_packed)
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

**Comment by Tracy-blue** [comment]
Hello, I have encountered the same problem. How did you solve it?
