### ISSUE TITLE
Questions about height optimization of vertices

### ISSUE THREAD

**Issue by runnerhdh** [DRosemei/RoMe#39]
Thanks for your great work! 
As #30 discussed, the whole work is sensitive to the initial value of the vertex height, and it is difficult for the MLP network to learn inclined planes. This is indeed the case after my experiment.
The ideas of 3dgs and your paper are similar. Have you tried the effect of 3dgs on the road reconstruction task? Is the optimization of 3dgs for gaussian center positions (analogy: vertices given inaccurate initial height values) also very limited? 
If I can only obtain the initial point cloud of the road surface with an accuracy within 0.5m, are there any good ways to optimize it? Very much looking forward to your reply~

**Comment by DRosemei** [comment]
@runnerhdh We have implemented 3dgs to street views but not only for road surface. We found that road surface can not be learned well even if we use lidar points to init, if you let points to split randomly. So if you want to optimize road surface with an accuracy within 0.5m, it could be hard. You can refer SuGAR, GaMes, ..., to make points attach on surface or use good initial points.

**Comment by runnerhdh** [comment]
Thank you for your reply. Looking forward to your great 3dgs work~. 
In addition, does 3dgs have high accuracy requirements for initial points (such as sparse sfm point clouds) in street scenes?

**Comment by DRosemei** [comment]
@runnerhdh Good initial points are important otherwise you need other methods to limit points learning. You can refer https://arxiv.org/pdf/2402.14650.pdf for infomation.
