### ISSUE TITLE
Subpar reconstruction result in some regions of the road

### ISSUE THREAD

**Issue by LevinJ** [DRosemei/RoMe#40]
With a dataset collected by myself, the overall Rome road surface reconstruction result is quite good. However, I also notice one region looks a bit off, specifically, the lane line in this regions is not straight, and its distance to neighboring lane line is slightly larger.

I highlighted the erroneous region with a black box in below images. Considering the fact that the lane lines in other regions look normal, I keep wondering what might be the possible causes for such problems, and what can be done to correct it.

![bev_rgb_7_32166d00beb3ff88a24f](https://github.com/DRosemei/RoMe/assets/1629014/b6e3403a-0f88-44db-a128-f6572f680b22)
![bev_seg_7_613d0676ff794b919732](https://github.com/DRosemei/RoMe/assets/1629014/d2f3f7c4-f5e8-4625-9eea-f61228427a7e)

**Comment by DRosemei** [comment]
Sorry for late reply. You can check final mesh file, it may be something wrong in bev elevations. For solution, you can use SfM/MVS points to limit bev elevations.

**Comment by LevinJ** [comment]
Thanks a lot for your kind pointer. I will try using colmap MVS points to initialize the mesh. Just to confirm, currently initializing bev mesh based on point clouds are not supported in the Rome github codes, and I have to add this part myself, is this correct?

**Comment by DRosemei** [comment]
Yes, you can do it yourself:)
