### ISSUE TITLE
Problem about BEV render

### ISSUE THREAD

**Issue by zjulabwjt** [DRosemei/RoMe#42]
hi, @DRosemei thanks for your great work! I use my datasets run RoMe, but find in bev render, img is not a bev result. What wrong might cause this problem? Thanks for your help!
![image](https://github.com/DRosemei/RoMe/assets/129039345/622cd739-685c-41ed-a335-ebde4ed5ce81)

**Comment by DRosemei** [comment]
@zjulabwjt Sorry for late reply. You can check ego car poses and make sure they are mostly paralleled to road/ground.

**Comment by zjulabwjt** [comment]
> @zjulabwjt Sorry for late reply. You can check ego car poses and make sure they are mostly paralleled to road/ground.

@DRosemei thanks for your reply. I visualize my ego pose xyz,The range of z-axis variation of the vehicle's pose is 4.9 meter during movement. Besides, the trajectory nearly a straight line. I also found the trajectory before and after multiplying the vehicle's pose by the transform_normal2origin matrix does not match. Is it because the plane fitting algorithm fails in this case?
![image](https://github.com/DRosemei/RoMe/assets/129039345/e00d1e07-cc61-4f24-83e2-09dfab5414fb)

**Comment by zjulabwjt** [comment]
> @zjulabwjt Q: Is it because the plane fitting algorithm fails in this case? A: It may be yes. Plane fitting algorithm is not always good especially. You can skip this and "camera_height", use actual (but may not be accurate road elevations) to init/supervise/fix elevation mlp.

@DRosemei 
Thank you for your advice. Following your suggestions, I improved the effectiveness of road surface reconstruction using pre-trained z mlp. However, I still encounter some issues I'd like to consult you about. In our scenario, there are a large number of vehicles. Due to the removal of dynamic objects during the training process, this results in numerous holes in the final road surface. Is there any effective method to address this situation?
![image](https://github.com/DRosemei/RoMe/assets/129039345/cdc21bde-518a-4f40-9a08-a4ed325a035c)

**Comment by DRosemei** [comment]
@DRosemei It is unavoidable, so we use more than one clip to reconstruct the whole area

**Comment by zjulabwjt** [comment]
> @DRosemei It is unavoidable, so we use more than one clip to reconstruct the whole area

Thanks for your reply! Does multiple clip data refer to data collected multiple times from the same area at different times?
