### ISSUE TITLE
Problem about using multi-camera 

### ISSUE THREAD

**Issue by MrlynnBei** [DRosemei/RoMe#44]
Hi, thank you for sharing the great work!

Our vehicle is equipped with six cameras, mounted on the front, back, left, and right, each with a different height. I have tested cameras with similar heights and achieved good results. However, I found that when I use all the cameras, some of them have significantly different heights, resulting in poor performance.

The code below only uses one camera height to estimate flat plane. I would like to know how I should modify the code to adapt to these multiple cameras？Any reply would be appreciated.

`        # 6. estimate flat plane
        self.file_check()
        self.label_valid_check()
        ref_camera2world_all = np.array(self.ref_camera2world_all)
        transform_normal2origin = robust_estimate_flatplane(np.array(ref_camera2world_all)[:, :3, 3]).astype(np.float32)
        transform_normal2origin[0, 3] = -self.choose_pt[0]
        transform_normal2origin[1, 3] = -self.choose_pt[1]
        transform_normal2origin[2, 3] += self.camera_height
        self.ref_camera2world_all = transform_normal2origin[None] @ self.ref_camera2world_all

**Comment by DRosemei** [comment]
@MrlynnBei Hi, you can refer https://github.com/DRosemei/RoMe/issues/42 for help. The estimated flat plane is not always good.

**Comment by MrlynnBei** [comment]
> @MrlynnBei Hi, you can refer #42 for help. The estimated flat plane is not always good.

Okk. Thanks!  And I have another question: Can the world coordinate system of the camera pose be an ENU system? or Can the camera pose be expressed in ENU coordinates?（tf_enu_cami）？

I saw the code that transform the tf_cam0_cami to tf_chassis_cami：(Am I understanding this correctly?)
camera_poses = self.camera2chassis @ camera_poses  # refrece to chassis

Any reply would be appreciated.

**Comment by DRosemei** [comment]
@MrlynnBei We use local corrdinate systems and save a tranform from local to global coordinate. It would be better for understanding and reconstruction.
