### ISSUE TITLE
colmap sfm scale

### ISSUE THREAD

**Issue by LevinJ** [DRosemei/RoMe#45]
Hi, I am trying colmap sfm point cloud to initialize Rome road surface mesh. As we know, colmap sfm reconstruction is scaleless, how do you usually determine the scale so that it can be used in Rome? Thanks.

**Comment by DRosemei** [comment]
@LevinJ You can use other sensors like imu, gps to get a real scale and align colmap poses to it

**Comment by LevinJ** [comment]
Got it, colmap Geo-registration is surely a good way to achieve this, Thanks @DRosemei.

**Comment by yuancaimaiyi** [comment]
@LevinJ  You can use the code in my repository to restore scale and large scene construction https://github.com/yuancaimaiyi/colmap-fusion-gps
