### ISSUE TITLE
Rendered images in evaluation

### ISSUE THREAD

**Issue by MinminYang33** [DRosemei/RoMe#46]
Hi @DRosemei,

With the trained mesh model and pose model, I evaluate it on the same scene. The rendered image is very different from the groundtruth image. And the mIoU is about 12%. It looks like the camera position is not correct. But I didn't change any code for loading the sample's extrinsic. So, is it because the generated mesh is problematic? Thank you in advance. 
![eval_95-blend](https://github.com/DRosemei/RoMe/assets/170973528/1132c9ec-9212-4ae6-90c4-b61584eb36c9)
Fig. 1 The blend image
![eval_95-gt](https://github.com/DRosemei/RoMe/assets/170973528/ee847d5a-3653-4f2d-b4ed-9fc566c46086)
Fig. 2 The gt image
![eval_95-render](https://github.com/DRosemei/RoMe/assets/170973528/0fb08563-5bfb-4853-a38d-507e7507cc9a)
Fig. 3. The rendered image
![eval_95-vis_gt_seg](https://github.com/DRosemei/RoMe/assets/170973528/d1135aa9-c2f1-44bb-ba82-fe0e20e12f91)
Fig. 4 The gt segmentation map
![eval_95-vis_seg](https://github.com/DRosemei/RoMe/assets/170973528/4e4aed57-7021-43a1-854e-eaf2b9fb4775)
Fig. 5 The predicted segmentation map

**Comment by MinminYang33** [comment]
I've also rendered the BEV from the saved mesh, and it looks correct.
[
![eval_render_bev](https://github.com/DRosemei/RoMe/assets/170973528/9c210427-0254-41af-bc39-0eeac756dfff)
](url)

**Comment by manymuch** [comment]
Fixed in https://github.com/DRosemei/RoMe/commit/d3ef283358bacc0b88d966a68cd85e75619c5a41

**Comment by Chatoyant19** [comment]
I am facing the same issue.How did you fix it?
