### ISSUE TITLE
segment problem when using custom dataset

### ISSUE THREAD

**Issue by Lin239522** [DRosemei/RoMe#47]
To build the semantic segmentation dataset, I ran scripts/mask2former_infer/infer.sh

```
export CUDA_VISIBLE_DEVICES=0
/home/ubuntu/anaconda3/envs/rome/bin/python3.8 /home/ubuntu/Project/RoMe/scripts/mask2former_infer/inference.py  \
  --config-file /home/ubuntu/Project/Mask2Former/configs/mapillary-vistas/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_300k.yaml \
  --opts MODEL.WEIGHTS /home/ubuntu/Project/Mask2Former/configs/mapillary-vistas/semantic-segmentation/swin/model_final_90ee2d.pkl
```

  And in inference.py, change the folder path to the path of the custom dataset

However, there are noises similar to the boundary on render_gt_seg_x.png . Can you tell me whether this will affect the rendering result? How can I remove these noises?
render_gt_seg:
![render_gt_seg_4_430f782ec4894065ae67](https://github.com/DRosemei/RoMe/assets/98506511/7b51a6d7-e79c-472c-958b-d632c5a40d81)
seg_sequences:
![1712049681498544301](https://github.com/DRosemei/RoMe/assets/98506511/9b646faa-5baa-4759-ae22-2ca8f06e4d32)
sequences:
![1712049681498544301](https://github.com/DRosemei/RoMe/assets/98506511/58d4f251-4ec2-4b78-a295-8be88a241597)

**Comment by DRosemei** [comment]
@Lin239522 You may need use cv2.INTER_NEAREST to resize semantic images.

**Comment by Lin239522** [comment]
> @Lin239522 You may need use cv2.INTER_NEAREST to resize semantic images.

 @DRosemei Thanks for the quick response！
 However, I did not modify the resize code in the __getitem__ function in RoMe.：RGB image resize uses cv2.INTER_LINEAR, and semantic segmentation image resize uses cv2.INTER_NEAREST.
```
 K = self.cameras_K[idx]
 D = self.distortion
 h, w = input_image.shape[:2]
 input_image = cv2.fisheye.undistortImage(input_image, K, D, Knew=K, new_size=(w, h))
 resized_image = cv2.resize(input_image, dsize=self.resized_image_size, interpolation=cv2.INTER_LINEAR)
…
 label = cv2.fisheye.undistortImage(label, K, D, Knew=K, new_size=(w, h))
 resized_label = cv2.resize(label, dsize=self.resized_image_size, interpolation=cv2.INTER_NEAREST)
```
In addition, in the configuration file, I set the image size to be the same as the input image (because I saw that you did this in the kitti configuration)
```
image_width: 3840
image_height: 1536
```
Is there anything wrong with my above operation?

**Comment by Lin239522** [comment]
When I reduce the image size in config to 960*384, the problem still exists
![render_gt_seg_4_64f215e4f354d68a9462](https://github.com/DRosemei/RoMe/assets/98506511/bf5139ad-dde0-44de-90e9-15eabfbef139)

**Comment by DRosemei** [comment]
@Lin239522  
`label = cv2.fisheye.undistortImage(label, K, D, Knew=K, new_size=(w, h))` may cause the problem.

**Comment by Lin239522** [comment]
> @Lin239522 `label = cv2.fisheye.undistortImage(label, K, D, Knew=K, new_size=(w, h))` may cause the problem.
Thank you for your suggestion！！  ·v·
This is the result without de-distortion. You can see that the lane lines on the road are curved.
![bev_rgb_7_b3be2ffe91e149b5368f](https://github.com/DRosemei/RoMe/assets/98506511/6a5e428f-7c97-4536-893a-d386da8e084a)
but the same problem occurred  QAQ
![render_gt_seg_5_0bcb4dbed46eab7da80f](https://github.com/DRosemei/RoMe/assets/98506511/d5f1875e-72bf-4f11-870b-9349138d86ba)
I am wondering that，in the visualized_output of mask2former， the boundaries of each category are drawn . Could this be the reason for the result?

**Comment by DRosemei** [comment]
@Lin239522  You can visualize label image before and after "cv2.fisheye.undistortImage" in source resolution to check.

**Comment by Lin239522** [comment]
I directly use the color map to map the output grayscale image of mask2former
![1712049675031863029](https://github.com/DRosemei/RoMe/assets/98506511/90bace07-5d63-4a1a-b92c-1d6f48cffda4)
```
color_map = np.zeros((256, 1, 3), dtype='uint8')
color_map[:, :, :] = [0, 0, 0]         # mask
color_map[7, :, :] = [0, 0, 255]       # all lane         车道线（蓝）
color_map[8, :, :] = [0, 0, 255]       # all lane         车道线（蓝）
color_map[14, :, :] = [0, 0, 255]       # all lane         车道线（蓝）
color_map[23, :, :] = [0, 0, 255]       # all lane         车道线（蓝）
color_map[24, :, :] = [0, 0, 255]       # all lane         车道线（蓝）
color_map[2, :, :] = [255, 0, 0]       # curb             路沿  （红）
color_map[9, :, :] = [255, 0, 0]       # curb             路沿  （红）
color_map[13, :, :] = [211, 211, 211]   # road and manhole 路面 （灰色）
color_map[4, :, :] = [157, 234, 50]    # background       背景-不重要元素（嫩草绿）
```
![colored_image](https://github.com/DRosemei/RoMe/assets/98506511/d5651b2e-5afd-4ba1-8a78-ad0d2ddd697e)
You can clearly see the boundary problem. I think this problem is caused by mask2former, that is, there are these "boundaries" on the grayscale image itself.

**Comment by DRosemei** [comment]
@Lin239522 Please visualize label image before "cv2.fisheye.undistortImage", that is visualizing fisheye image by colormap. "cv2.fisheye.undistortImage" will interpolate labels and use cv2.remap instead

**Comment by Lin239522** [comment]
@DRosemei This photo is  label image before "cv2.fisheye.undistortImage", I just  ran infer.sh, and then  visualizing fisheye image by colormap. Could this be due to the limitations of the official model, which cannot identify domestic roads?
![image](https://github.com/DRosemei/RoMe/assets/98506511/3632336f-038a-42e4-9f93-764e5c241ac9)

**Comment by Lin239522** [comment]
Dear @DRosemei ,Thank you again for your enthusiastic answer.
I have another question.
 What is the reason for the box-like defects that appear in the rendered image?
 
 
 eval_117-render.png:
![image](https://github.com/DRosemei/RoMe/assets/98506511/79ca851b-b17f-43fb-bdbc-e5adeae8ff3a)
 eval_117-vis_gt_seg.png:
![image](https://github.com/DRosemei/RoMe/assets/98506511/d0f6c72e-4ec2-467b-8814-612054820d66)
 eval_117-vis_seg.png:
![image](https://github.com/DRosemei/RoMe/assets/98506511/d184b00e-0a1c-4cea-9e64-e504c6febc1d)
 eval_117-blend.png:
![image](https://github.com/DRosemei/RoMe/assets/98506511/b35ab43f-8d2b-4b50-ab55-aa2c360e2ff2)

**Comment by Lin239522** [comment]
Hey @DRosemei , you are right! The cv2.fisheye.undistortImage function did cause the problem. How can I solve it? Should I use FishEyeCameras to render the mesh instead of using cv2.fisheye.undistortImage on the input images?

**Comment by DRosemei** [comment]
@Lin239522 
1. "box-like defects" are caused by pytorch3D, it may happen somtimes
2. Use cv2.remap to undistort fisheye label by cv2.INTER_NEAREST
```
cv_image = cv2.imread(image_path, -1)

mapx, mapy = cv2.initUndistortRectifyMap(k, d, None, k, (cv_image.shape[1], cv_image.shape[0]), cv2.CV_32FC1)

cv_image_undistorted = cv2.remap(cv_image, mapx, mapy, cv2.INTER_NEAREST)
```

**Comment by Lin239522** [comment]
thanks! it works  ·v·
