### ISSUE TITLE
how to evaluate the accuracy of 3Dmesh

### ISSUE THREAD

**Issue by Lin239522** [DRosemei/RoMe#48]
@DRosemei hey~
How can I quantitatively judge the accuracy of 3Dmesh? For example, I want to know whether the coordinates of the lane lines are accurate. Can I compare them with the results of the laser or project them onto a satellite map?
Thanks again for your patience

**Comment by DRosemei** [comment]
@Lin239522 Sorry for late reply. It is hard to evaluate accuracy. Extrinsics, poses and elevations all contribute to the accuracy.  
A simple way is as follows:
1. Label on BEV
2. Transform 2d labels to 3d labels by elevations
3. Reproject 3d labels to cameras
4. Compute reprojected labels errors in image space
