### ISSUE TITLE
How to make my own data set

### ISSUE THREAD

**Issue by gwy0o0** [DRosemei/RoMe#49]
Dear author, I want to make my own data set, but I don't know how to make my own data set. Can you help me to make my own data set? Thank you for your answer.

**Comment by DRosemei** [comment]
You need to define a dataset to read poses, RGB images and semantic images. A simple way is to convert your data to kitti format.

**Comment by gwy0o0** [comment]
> You need to define a dataset to read poses, RGB images and semantic images. A simple way is to convert your data to kitti format.

thanks！
