### ISSUE TITLE
Can you provided the data process script for kitti or nuscene?

### ISSUE THREAD

**Issue by rockywind** [DRosemei/RoMe#5]
Hi, thank you for sharing the great work.
Can you provided the data process script for kitti or nuscene?
I met the error below wnen I ran the maskformer.
![image](https://github.com/DRosemei/RoMe/assets/14838781/eb0af0e2-b602-43b5-b96c-fa3028d62db3)

I think the error is from the setting of segmentation clsss .
 
![image](https://github.com/DRosemei/RoMe/assets/14838781/1f4f9fef-6ad4-4786-9921-107c337b7f8f)
So, can you provided the data process script for kitti or nuscene?
This is my infer script
````
python demo/demo_my.py \
--config-file /rockywin.wang/NeRF/Mask2Former/configs/mapillary-vistas/panoptic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_300k.yaml \
--input /rockywin.wang/NeRF/RoMe/RoMe_data/nuscenes/samples/CAM_FRONT/ \
--output /rockywin.wang/NeRF/suds/data/kitti/20230201-15-13-45_obj_nerf_norm_0_100/seg \ 
--predictions /rockywin.wang/NeRF/suds/data/kitti/20230201-15-13-45_obj_nerf_norm_0_100/seg \
--opts MODEL.WEIGHTS /SHFP12/02_bevdet/SceneRF/01_thrd_data/model_final_132c71_map_pano.pkl
````

**Comment by DRosemei** [comment]
@rockywind I update it [here](https://github.com/DRosemei/RoMe/tree/main/scripts/mask2former_infer) and you can refer to it.

**Comment by rockywind** [comment]
Hi, 
I met the error below When I put the maskformer_infer to mask2former folfer.
![image](https://github.com/DRosemei/RoMe/assets/14838781/a6334f7f-027a-46e2-9f10-cedbb2a9d3cf)
Can you share the whole mask2former folder.
