### ISSUE TITLE
作者您好，我想知道RoMe支持重建的路面元素都是些什么，或者说重建结果输出的标签都是哪几个类别？

### ISSUE THREAD

**Issue by gwy0o0** [DRosemei/RoMe#50]
我看论文写的类别有6类分别是：Road、Curb、Lane、Sidewalk、Terrain和Crosswalk，我们是主要支持这6类吗，其他的道路元素比如car也支持吗？感谢您的贡献，期待您的答复！

**Comment by DRosemei** [comment]
@gwy0o0 You can refer [here](https://github.com/DRosemei/RoMe/blob/main/datasets/nusc.py#L400).

**Comment by gwy0o0** [comment]
> @gwy0o0 You can refer [here](https://github.com/DRosemei/RoMe/blob/main/datasets/nusc.py#L400).
谢谢！
