### ISSUE TITLE
bev resolution to 0.02 will cause subtriangle count overflow

### ISSUE THREAD

**Issue by liuzy10** [DRosemei/RoMe#54]
@DRosemei 大佬你好，我将bev resolution改为0.02，也就是2cm，测试一个长度约80m的数据，得到的vertex有将近900w个，在render时因为顶点数太多报错，请问有啥方法可以解决这个？ 

![img_v3_02dq_1cdef3ab-fc1f-435f-8596-8a7a460dc7dg](https://github.com/user-attachments/assets/b5c8ec59-0b13-420d-903a-cb0981b60b44)

有个疑问论文中有根据waypoint对mesh进行分块，但是处理每个waypoint数据进行render的mesh都是整个的大小？ 

![image](https://github.com/user-attachments/assets/7d6956a2-5437-446a-adb4-df6b8c2fa28a)

![image](https://github.com/user-attachments/assets/aab601cc-11f5-4b5c-baca-6a8af4abd31e)

**Comment by DRosemei** [comment]
@liuzy10 对，只是切断了梯度回传，仍然是render的整个mesh。可以参考其他人的后续工作 https://arxiv.org/pdf/2405.14342

**Comment by liuzy10** [comment]
谢谢，我这边是对原始的bev进行分块优化
