### ISSUE TITLE
On the normal vector direction of mesh results

### ISSUE THREAD

**Issue by gwy0o0** [DRosemei/RoMe#55]
Dear author, hello, I trained rome to get the mesh file in obj format. When I opened it with meshlab software, I found that its normal vector was inverse. Is the normal vector set in the code inverse? Is there any way to change the direction of the normal vector in the code? I look forward to your reply!
Mesh results of the paper scene0655
![EY1425O_I@3{Q@E 9J$D}A](https://github.com/user-attachments/assets/ed8eb8aa-fc6b-41fe-8d74-e613c34b7310)
This is the result of scene0655 opened by meshlab software.
![Uploading 5NKWN0ML`FJH]OXW8IJAR`A.png…]()

**Comment by gwy0o0** [comment]
This is the result of scene0655 opened by meshlab software.
![Uploading 5NKWN0ML`FJH]OXW8IJAR`A.png…]()

**Comment by gwy0o0** [comment]
![5NKWN0ML`FJH OXW8IJAR`A](https://github.com/user-attachments/assets/0902974c-80ed-4b94-bc14-47107975203e)

**Comment by gwy0o0** [comment]
This is the result of scene0655 opened by meshlab software.
![5NKWN0ML`FJH OXW8IJAR`A](https://github.com/user-attachments/assets/6191d757-58c3-43d5-9d5e-6880b0420852)

**Comment by DRosemei** [comment]
@gwy0o0 仓库上的代码对bev的转换和对应mesh的转换还是很早以前的实验版本，很多旋转会比较麻烦。如果你只是想要旋转normal，看看是否用一些库手动转下？

**Comment by gwy0o0** [comment]
![3 NV2MZT~{$ U%M U6V22_I](https://github.com/user-attachments/assets/ff614a66-3944-4286-9403-a28bedd77df8)
你好，我在geometry.py中将原本代码替换为红框所示代码，使得角点顺序翻转，重新训练后得到的mesh文件法向量与论文一致。
