### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by christianll9** [DRosemei/RoMe#57]
Hi @DRosemei,

thanks for sharing your work! I noticed that the `LICENSE.md` file is missing from the repository. Would it be possible for you to include such a file with a free-software license such as MIT?

**Comment by DRosemei** [comment]
@christianll9 Thanks for pointing it out and we have added MIT license [here](https://github.com/DRosemei/RoMe/blob/main/LICENSE).
