### ISSUE TITLE
How to obtain a model mesh with height variation

### ISSUE THREAD

**Issue by 16Huzeyu** [DRosemei/RoMe#6]
Hi, thank you for sharing the great work!
I have tried this work with nusc dataset and I can obtain bevobj without height variation. 
![image](https://github.com/DRosemei/RoMe/assets/20391912/571d2bcc-4ae8-4066-a5c3-dc690fbdd89f)

So if there is anyway for me to get mesh result like this which has height variation
![image](https://github.com/DRosemei/RoMe/assets/20391912/07ff2c4f-4a88-4116-8731-8fc06369ca14)

**Comment by DRosemei** [comment]
@16Huzeyu The version we released could only reconstruct slight height variation and you can visulize height as shown in Fig,4. BEV elevation
![image](https://github.com/DRosemei/RoMe/assets/27892562/ca969d0d-053e-4580-a2db-7f1f29de552e). 
You can add more supervision to reconstruct steep road surface.

**Comment by 16Huzeyu** [comment]
@DRosemei Thank you for your reply!
I will have a try

**Comment by rockywind** [comment]
@DRosemei @16Huzeyu 
Can you sharing the height visualization code?
