### ISSUE TITLE
I meet some problem when I  try use my custom dataset

### ISSUE THREAD

**Issue by 16Huzeyu** [DRosemei/RoMe#7]
This is nerfstudio dataset I try to add
import numpy as np
import cv2
from multiprocessing.pool import ThreadPool as Pool
from os.path import join
from copy import deepcopy
from tqdm import tqdm
from pyquaternion import Quaternion
from nuscenes.nuscenes import NuScenes
from nuscenes.utils.geometry_utils import transform_matrix
from skspatial.objects import Plane, Points
from datasets.base import BaseDataset
from utils.plane_fit import robust_estimate_flatplane
import json
from pathlib import Path

def load_from_json(filename: Path):
    """Load a dictionary from a JSON filename.

    Args:
        filename: The filename to load from.
    """
    assert filename.suffix == ".json"
    with open(filename, encoding="UTF-8") as file:
        return json.load(file)

class NeRFStudioDataset(BaseDataset):
    def __init__(self, configs):
        super().__init__()
        meta = load_from_json(Path(configs["base_dir"])/ "transforms.json")
        self.base_dir = configs["base_dir"]
        self.image_dir = configs["image_dir"]
        x_offset = -configs["center_point"]["x"] + configs["bev_x_length"]/2
        y_offset = -configs["center_point"]["y"] + configs["bev_y_length"]/2
        self.world2bev = np.asarray([
            [1, 0, 0, x_offset],
            [0, 1, 0, y_offset],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ], dtype=np.float32)
        self.resized_image_size = (configs["image_width"], configs["image_height"])
        self.choose_pt = [configs["choose_point"]["x"], configs["choose_point"]["y"]]       
    

        fx_fixed = "fl_x" in meta
        fy_fixed = "fl_y" in meta
        cx_fixed = "cx" in meta
        cy_fixed = "cy" in meta
        height_fixed = "h" in meta
        width_fixed = "w" in meta
        distort_fixed = False
        for distort_key in ["k1", "k2", "k3", "p1", "p2"]:
            if distort_key in meta:
                distort_fixed = True
                break
        self.camera_extrinsics = []
        height = []
        width = []
        self.camera_height = 1.6
        fx = float(meta["fl_x"])
        fy = float(meta["fl_y"])
        cx = float(meta["cx"])
        cy = float(meta["cy"])
        for idx,frame in enumerate(meta["frames"]):
            filepath = frame["file_path"]
            label_filepath = frame["mask_path"]
            fname = join(self.image_dir,filepath)
            #label_fname = Path(self.image_dir/label_filepath)

            if not fx_fixed:
                assert "fl_x" in frame, "fx not specified in frame"
                fx = (float(frame["fl_x"]))
            if not fy_fixed:
                assert "fl_y" in frame, "fy not specified in frame"
                fy = (float(frame["fl_y"]))
            if not cx_fixed:
                assert "cx" in frame, "cx not specified in frame"
                cx = (float(frame["cx"]))
            if not cy_fixed:
                assert "cy" in frame, "cy not specified in frame"
                cy = (float(frame["cy"]))
            if not height_fixed:
                assert "h" in frame, "height not specified in frame"
                height.append(int(frame["h"]))
            if not width_fixed:
                assert "w" in frame, "width not specified in frame"
                width.append(int(frame["w"]))
            intrinsic = np.asarray([[fx, 0, cx], [0, fy, cy], [0, 0, 1]])
            self.image_filenames_all.append(fname)
            self.camera_extrinsics.append(np.eye(4).astype(np.float32))
            self.ref_camera2world_all.append(np.array(frame["transform_matrix"]).astype(np.float32))
             
            self.cameras_idx_all.append(idx)
            self.cameras_K_all.append(intrinsic.astype(np.float32))

            self.label_filenames_all.append(label_filepath)

        self.file_check()
        #self.label_valid_check()
        ref_camera2world_all = np.array(self.ref_camera2world_all)
        print(ref_camera2world_all.shape)
        print("before plane estimation, z std = ", ref_camera2world_all[:, 2, 3].std())
        transform_normal2origin = robust_estimate_flatplane(np.array(ref_camera2world_all)[:, :3, 3]).astype(np.float32)
        transform_normal2origin[0, 3] = -self.choose_pt[0]
        transform_normal2origin[1, 3] = -self.choose_pt[1]
        transform_normal2origin[2, 3] += self.camera_height
        self.ref_camera2world_all = transform_normal2origin[None] @ self.ref_camera2world_all
        print("after plane estimation, z std = ", self.ref_camera2world_all[:, 2, 3].std())

        # 7. filter poses in bev range
        all_camera_xy = np.asarray(self.ref_camera2world_all)[:, :2, 3]
        available_mask_x = abs(all_camera_xy[:, 0]) < configs["bev_x_length"] // 2 + 10
        available_mask_y = abs(all_camera_xy[:, 1]) < configs["bev_y_length"] // 2 + 10
        available_mask = available_mask_x & available_mask_y
        available_idx = list(np.where(available_mask)[0])
        print(f"before poses filtering, pose num = {available_mask.shape[0]}")
        self.filter_by_index(available_idx)
        print(f"after poses filtering, pose num = {available_mask.sum()}")
        print(self.camera_extrinsics[11])
        print(self.ref_camera2world_all[11])

    def compute_chassis2world(self, samp):
        """transform sensor in world coordinate"""
        # comput current frame Homogeneous transformation matrix : from chassis 2 global
        pose_chassis2global = self.nusc.get("ego_pose", samp['ego_pose_token'])
        chassis2global = transform_matrix(pose_chassis2global['translation'],
                                          Quaternion(pose_chassis2global['rotation']),
                                          inverse=False)
        return chassis2global

    def compute_extrinsic(self, samp_a, samp_b):
        """transform from sensor_a to sensor_b"""
        sensor_a2chassis = self.compute_extrinsic2chassis(samp_a)
        sensor_b2chassis = self.compute_extrinsic2chassis(samp_b)
        sensor_a2sensor_b = np.linalg.inv(sensor_b2chassis) @ sensor_a2chassis
        return sensor_a2sensor_b

    def compute_extrinsic2chassis(self, samp):
        calibrated_sensor = self.nusc.get("calibrated_sensor", samp["calibrated_sensor_token"])
        rot = np.array((Quaternion(calibrated_sensor["rotation"]).rotation_matrix))
        tran = np.expand_dims(np.array(calibrated_sensor["translation"]), axis=0)
        sensor2chassis = np.hstack((rot, tran.T))
        sensor2chassis = np.vstack((sensor2chassis, np.array([[0, 0, 0, 1]])))  # [4, 4] camera 3D
        return sensor2chassis

    def file_check(self):
        image_paths = [join(self.base_dir, image_path) for image_path in self.image_filenames_all]
        label_paths = [join(self.image_dir, label_path) for label_path in self.label_filenames_all]
        image_exists = np.asarray(self.check_filelist_exist(image_paths))
        label_exists = np.asarray(self.check_filelist_exist(label_paths))
        available_index = list(np.where(image_exists * label_exists)[0])
        print(f"Drop {len(image_paths) - len(available_index)} frames out of {len(image_paths)} by file exists check")
        self.filter_by_index(available_index)

    def label_valid_check(self):
        label_paths = [join(self.image_dir, label_path) for label_path in self.label_filenames_all]
        label_valid = np.asarray(self.check_label_valid(label_paths))
        available_index = list(np.where(label_valid)[0])
        print(f"Drop {len(label_paths) - len(available_index)} frames out of {len(label_paths)} by label valid check")
        self.filter_by_index(available_index)

    def label_valid(self, label_name):
        label = cv2.imread(label_name, cv2.IMREAD_UNCHANGED)
        label_movable = label >= 52
        ratio_movable = label_movable.sum() / label_movable.size
        label_off_road = ((0 <= label) & (label <= 1)) | ((3 <= label) & (label <= 6)) | ((10 <= label) & (label <= 12)) \
            | ((15 <= label) & (label <= 22)) | ((25 <= label) & (label <= 40)) | (label >= 42)
        ratio_static = label_off_road.sum() / label_off_road.size
        if ratio_movable > 0.3 or ratio_static > 0.9:
            return False
        else:
            return True

    def check_label_valid(self, filelist):
        with Pool(32) as p:
            exist_list = p.map(self.label_valid, filelist)
        return exist_list

    def estimate_flatplane(self, lidar2world_all, lidar_height):
        xyz = lidar2world_all[:, :3, 3]
        points = Points(xyz)
        plane = Plane.best_fit(points)
        normal_z = np.asarray(plane.normal)
        origin_x = np.asarray([1, 0, 0])
        normal_y = np.cross(normal_z, origin_x)
        normal_y = normal_y / np.linalg.norm(normal_y)
        normal_x = np.cross(normal_y, normal_z)
        normal_x = normal_x / np.linalg.norm(normal_x)
        rotation_origin2normal = np.asarray([normal_x, normal_y, normal_z]).T
        translation_origin2normal = np.asarray(plane.point)
        transform_origin2normal = np.eye(4)
        transform_origin2normal[:3, :3] = rotation_origin2normal
        transform_origin2normal[:3, 3] = translation_origin2normal
        transform_normal2origin = np.linalg.inv(transform_origin2normal)
        transform_normal2origin[2, 3] += lidar_height
        return transform_normal2origin.astype(np.float32)

    def filter_by_index(self, index):
        self.image_filenames_all = [self.image_filenames_all[i] for i in index]
        self.label_filenames_all = [self.label_filenames_all[i] for i in index]
        self.ref_camera2world_all = [self.ref_camera2world_all[i] for i in index]
        self.cameras_K_all = [self.cameras_K_all[i] for i in index]
        self.cameras_idx_all = [self.cameras_idx_all[i] for i in index]

    def set_waypoint(self, center_xy, radius):
        center_xy = np.asarray([center_xy[0], center_xy[1]], dtype=np.float32)
        all_camera_xy = np.asarray(self.ref_camera2world_all)[:, :2, 3]
        distances = np.linalg.norm(all_camera_xy - center_xy, ord=np.inf, axis=1)
        activated_idx = list(np.where(distances < radius)[0])
        self.image_filenames = [self.image_filenames_all[i] for i in activated_idx]
        self.label_filenames = [self.label_filenames_all[i] for i in activated_idx]
        self.ref_camera2world = [self.ref_camera2world_all[i] for i in activated_idx]
        self.cameras_idx = [self.cameras_idx_all[i] for i in activated_idx]
        self.cameras_K = [self.cameras_K_all[i] for i in activated_idx]
        self.ref_camera2world = [self.ref_camera2world_all[i] for i in activated_idx]
        self.activated_idx = activated_idx

    def label2mask(self, label):
        # Bird, Ground Animal, Curb, Fence, Guard Rail,
        # Barrier, Wall, Bike Lane, Crosswalk - Plain, Curb Cut,
        # Parking, Pedestrian Area, Rail Track, Road, Service Lane,
        # Sidewalk, Bridge, Building, Tunnel, Person,
        # Bicyclist, Motorcyclist, Other Rider, Lane Marking - Crosswalk, Lane Marking - General,
        # Mountain, Sand, Sky, Snow, Terrain,
        # Vegetation, Water, Banner, Bench, Bike Rack,
        # Billboard, Catch Basin, CCTV Camera, Fire Hydrant, Junction Box,
        # Mailbox, Manhole, Phone Booth, Pothole, Street Light,
        # Pole, Traffic Sign Frame, Utility Pole, Traffic Light, Traffic Sign (Back),
        # Traffic Sign (Front), Trash Can, Bicycle, Boat, Bus,
        # Car, Caravan, Motorcycle, On Rails, Other Vehicle,
        # Trailer, Truck, Wheeled Slow, Car Mount, Ego Vehicle
        mask = np.ones_like(label)
        label_off_road = ((0 <= label) & (label <= 1)) | ((3 <= label) & (label <= 6)) | ((10 <= label) & (label <= 12)) \
            | ((16 <= label) & (label <= 22)) | ((25 <= label) & (label <= 28)) | ((30 <= label) & (label <= 40)) | (label >= 42)

        # dilate itereation 2 for moving objects
        label_movable = label >= 52
        kernel = np.ones((10, 10), dtype=np.uint8)
        label_movable = cv2.dilate(label_movable.astype(np.uint8), kernel, 2).astype(np.bool_)

        label_off_road = label_off_road | label_movable
        mask[label_off_road] = 0
        label[~(mask.astype(np.bool_))] = 64
        mask = mask.astype(np.float32)
        return mask, label

    def __getitem__(self, idx):
        sample = dict()
        sample["idx"] = idx
        sample["camera_idx"] = self.cameras_idx[idx]
        sample["camera2ref"] = self.camera_extrinsics[sample["camera_idx"]]

        # read image
        image_path = self.image_filenames[idx]
        sample["image_path"] = image_path
        input_image = cv2.imread(join(self.base_dir, image_path))
        crop_cy = int(self.resized_image_size[1] / 2)
        K = self.cameras_K[idx].astype(np.float32)
        origin_image_size = input_image.shape
        resized_image = cv2.resize(input_image, dsize=self.resized_image_size, interpolation=cv2.INTER_LINEAR)
        resized_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB)
        resized_image = resized_image[crop_cy:, :, :]  # crop the sky
        sample["image"] = (np.asarray(resized_image)/255.0).astype(np.float32)

        # read label
        label_path = join(self.image_dir, self.label_filenames[idx])
        label = cv2.imread(label_path, cv2.IMREAD_UNCHANGED)
        resized_label = cv2.resize(label, dsize=self.resized_image_size, interpolation=cv2.INTER_NEAREST)
        mask, label = self.label2mask(resized_label)

        label = self.remap_semantic(label).astype(np.int64)

        mask = mask[crop_cy:, :]  # crop the sky
        label = label[crop_cy:, :]
        sample["static_mask"] = mask
        sample["static_label"] = label

        cv_camera2world = self.ref_camera2world[idx] @ sample["camera2ref"]  # fsd camera to fsd world
        camera2world = self.world2bev @ cv_camera2world
        sample["world2camera"] = np.linalg.inv(camera2world)
        resized_K = deepcopy(K)
        width_scale = self.resized_image_size[0]/origin_image_size[1]
        height_scale = self.resized_image_size[1]/origin_image_size[0]
        resized_K[0, :] *= width_scale
        resized_K[1, :] *= height_scale
        resized_K[1, 2] -= crop_cy
        sample["camera_K"] = resized_K
        sample["image_shape"] = np.asarray(sample["image"].shape)[:2]
        sample = self.opencv_camera2pytorch3d_(sample)
        return sample

    @ property
    def label_remaps(self):
        colors = np.ones((256, 1), dtype="uint8")
        colors *= 6          # background
        colors[7, :] = 1     # Lane marking
        colors[8, :] = 1
        colors[14, :] = 1
        colors[23, :] = 1
        colors[24, :] = 1
        colors[2, :] = 2     # curb
        colors[9, :] = 2     # curb cut
        colors[41, :] = 3    # Manhole
        colors[13, :] = 3    # road
        colors[15, :] = 4    # sidewalk
        colors[29, :] = 5    # terrain
        return colors

    @ property
    def origin_color_map(self):
        colors = np.zeros((256, 1, 3), dtype='uint8')
        colors[0, :, :] = [165, 42, 42]  # Bird
        colors[1, :, :] = [0, 192, 0]  # Ground Animal
        colors[2, :, :] = [196, 196, 196]  # Curb
        colors[3, :, :] = [190, 153, 153]  # Fence
        colors[4, :, :] = [180, 165, 180]  # Guard Rail
        colors[5, :, :] = [90, 120, 150]  # Barrier
        colors[6, :, :] = [102, 102, 156]  # Wall
        colors[7, :, :] = [128, 64, 255]  # Bike Lane
        colors[8, :, :] = [140, 140, 200]  # Crosswalk - Plain
        colors[9, :, :] = [170, 170, 170]  # Curb Cut
        colors[10, :, :] = [250, 170, 160]  # Parking
        colors[11, :, :] = [96, 96, 96]  # Pedestrian Area
        colors[12, :, :] = [230, 150, 140]  # Rail Track
        colors[13, :, :] = [128, 64, 128]  # Road
        colors[14, :, :] = [110, 110, 110]  # Service Lane
        colors[15, :, :] = [244, 35, 232]  # Sidewalk
        colors[16, :, :] = [150, 100, 100]  # Bridge
        colors[17, :, :] = [70, 70, 70]  # Building
        colors[18, :, :] = [150, 120, 90]  # Tunnel
        colors[19, :, :] = [220, 20, 60]  # Person
        colors[20, :, :] = [255, 0, 0]  # Bicyclist
        colors[21, :, :] = [255, 0, 100]  # Motorcyclist
        colors[22, :, :] = [255, 0, 200]  # Other Rider
        colors[23, :, :] = [200, 128, 128]  # Lane Marking - Crosswalk
        colors[24, :, :] = [255, 255, 255]  # Lane Marking - General
        colors[25, :, :] = [64, 170, 64]  # Mountain
        colors[26, :, :] = [230, 160, 50]  # Sand
        colors[27, :, :] = [70, 130, 180]  # Sky
        colors[28, :, :] = [190, 255, 255]  # Snow
        colors[29, :, :] = [152, 251, 152]  # Terrain
        colors[30, :, :] = [107, 142, 35]  # Vegetation
        colors[31, :, :] = [0, 170, 30]  # Water
        colors[32, :, :] = [255, 255, 128]  # Banner
        colors[33, :, :] = [250, 0, 30]  # Bench
        colors[34, :, :] = [100, 140, 180]  # Bike Rack
        colors[35, :, :] = [220, 220, 220]  # Billboard
        colors[36, :, :] = [220, 128, 128]  # Catch Basin
        colors[37, :, :] = [222, 40, 40]  # CCTV Camera
        colors[38, :, :] = [100, 170, 30]  # Fire Hydrant
        colors[39, :, :] = [40, 40, 40]  # Junction Box
        colors[40, :, :] = [33, 33, 33]  # Mailbox
        colors[41, :, :] = [100, 128, 160]  # Manhole
        colors[42, :, :] = [142, 0, 0]  # Phone Booth
        colors[43, :, :] = [70, 100, 150]  # Pothole
        colors[44, :, :] = [210, 170, 100]  # Street Light
        colors[45, :, :] = [153, 153, 153]  # Pole
        colors[46, :, :] = [128, 128, 128]  # Traffic Sign Frame
        colors[47, :, :] = [0, 0, 80]  # Utility Pole
        colors[48, :, :] = [250, 170, 30]  # Traffic Light
        colors[49, :, :] = [192, 192, 192]  # Traffic Sign (Back)
        colors[50, :, :] = [220, 220, 0]  # Traffic Sign (Front)
        colors[51, :, :] = [140, 140, 20]  # Trash Can
        colors[52, :, :] = [119, 11, 32]  # Bicycle
        colors[53, :, :] = [150, 0, 255]  # Boat
        colors[54, :, :] = [0, 60, 100]  # Bus
        colors[55, :, :] = [0, 0, 142]  # Car
        colors[56, :, :] = [0, 0, 90]  # Caravan
        colors[57, :, :] = [0, 0, 230]  # Motorcycle
        colors[58, :, :] = [0, 80, 100]  # On Rails
        colors[59, :, :] = [128, 64, 64]  # Other Vehicle
        colors[60, :, :] = [0, 0, 110]  # Trailer
        colors[61, :, :] = [0, 0, 70]  # Truck
        colors[62, :, :] = [0, 0, 192]  # Wheeled Slow
        colors[63, :, :] = [32, 32, 32]  # Car Mount
        colors[64, :, :] = [120, 10, 10]  # Ego Vehicle
        # colors[65, :, :] = [0, 0, 0] # Unlabeled
        return colors

    @property
    def num_class(self):
        return 7

    @ property
    def filted_color_map(self):
        colors = np.zeros((256, 1, 3), dtype='uint8')
        colors[0, :, :] = [0, 0, 0]         # mask
        colors[1, :, :] = [0, 0, 255]       # all lane
        colors[2, :, :] = [255, 0, 0]       # curb
        colors[3, :, :] = [211, 211, 211]   # road and manhole
        colors[4, :, :] = [0, 191, 255]     # sidewalk
        colors[5, :, :] = [152, 251, 152]   # terrain
        colors[6, :, :] = [157, 234, 50]    # background
        return colors

But the render image is whole white , what mistake do I make?

**Comment by DRosemei** [comment]
@16Huzeyu Poses in your frame may use opengl coordinates, while we use opencv coordinates. You can check for that.

**Comment by 16Huzeyu** [comment]
@DRosemei Thank you for your reply！The following is one of the pose I use，it's openCV
            "file_path": "images/cam_fl/cam_fl_7056.png",
            "transform_matrix": [
                [
                    0.058115019077757325,
                    -0.9937210028790265,
                    0.09560969090365867,
                    0.553701041070004
                ],
                [
                    0.9567113245786762,
                    0.028079310442992087,
                    -0.28968084808623495,
                    -1.444330660782936
                ],
                [
                    0.28517728868285813,
                    0.1083056820399896,
                    0.9523359665881291,
                    6.337180474850118
                ],
                [
                    0.0,
                    0.0,
                    0.0,
                    1.0
                ]
            ],
            "colmap_im_id": 1,
            "w": 1920,
            "h": 1080,
            "fl_x": 4005.972857677684,
            "fl_y": 3831.3128328513726,
            "cx": 960.0,
            "cy": 540.0,
            "k1": -0.296500708721993,
            "k2": 0.12750465117837975,
            "p1": 0.007696403463706885,
            "p2": -0.0021737904982136796,
            "camera_model": "OPENCV",

**Comment by DRosemei** [comment]
@16Huzeyu Could you provide some logs?

**Comment by 16Huzeyu** [comment]
@DRosemei
这是LOG
1 [[ 3.7434418e-02  5.2238866e-03  9.9928546e-01  2.5622089e+01]
 2  [ 9.9928772e-01 -4.9690576e-03 -3.7408527e-02 -1.0727676e+00]
 3  [ 4.7700889e-03  9.9997401e-01 -5.4061795e-03 -1.1638844e+00]
 4  [ 0.0000000e+00 -0.0000000e+00 -0.0000000e+00  1.0000000e+00]]
 5 Drop 0 frames out of 192 by file exists check
 6 (192, 4, 4)
 7 before plane estimation, z std =  0.41458207
 8 after plane estimation, z std =  0.006886143
 9 before poses filtering, pose num = 192
10 after poses filtering, pose num = 192
11 [[ 3.7413038e-02 -2.9975113e-02  9.9885017e-01  2.5646996e+01]
12  [ 9.9929911e-01 -1.4409702e-04 -3.7434176e-02 -1.0783709e+00]
13  [ 1.2660250e-03  9.9955064e-01  2.9948715e-02 -6.2021613e-03]
14  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
15 Get 192 images for mapping
16 vertices_rgb optimization is ON
17 vertices_label optimization is OFF
18 vertices_z optimization is ON
19 rotations optimization is ON
20 translations optimization is ON
21 Before cutting,  3467733 vertices, 6928000 faces
22   0%|                                                                                                                                                                                                                                                           | 0/7 [00:00<?, ?it/s]/home/ubuntu/anaconda3/envs/rome/lib/python3.8/site-packages/pytorch3d/structures/meshes.py:1097: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
23   self._edges_packed = torch.stack([u // V, u % V], dim=1)
24 After cutting,  50801 vertices, 100388 faces
25 [{'params': Parameter containing:
26 tensor([[[0., 0., 0.],
27          [0., 0., 0.],
28          [0., 0., 0.],
29          ...,
30          [0., 0., 0.],
31          [0., 0., 0.],
32          [0., 0., 0.]]], device='cuda:0', requires_grad=True), 'lr': 0.1}]
33 epoch-1: get 1 waypoints
34 + 192, num_frames = 192
35 (188, 1241)
36 epoch-2: get 1 waypoints
37 + 192, num_frames = 192
38 Epoch: 7, loss = 0.0012: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:01<00:00,  8.82s/it]
39 epoch-3: get 1 waypoints
40 + 192, num_frames = 192
41 epoch-4: get 1 waypoints
42 + 192, num_frames = 192
43 epoch-5: get 1 waypoints
44 + 192, num_frames = 192
45 epoch-6: get 1 waypoints
46 + 192, num_frames = 192
47 epoch-7: get 1 waypoints
48 + 192, num_frames = 192
49 Traceback (most recent call last):
50   File "scripts/train.py", line 336, in <module>
51     train(configs)
52   File "scripts/train.py", line 321, in train
53     save_cut_label_mesh(mesh[0], join(logger.dir, f"bev_label_mesh_epoch_{epoch}.obj"), dataset.filted_color_map)
54   File "/home/ubuntu/project/nerf/RoMe/utils/visualizer.py", line 85, in save_cut_label_mesh
55     vert_labels = vert_labels.argmax(axis=1)
56 ValueError: attempt to get argmax of an empty sequence


有遇到mask之后loss就为0了的问题，然后我尝试过去掉mask算render_loss大概0.7左右大，是这个loss就固定了，imagefeature并不会被优化

**Comment by 16Huzeyu** [comment]
@DRosemei 还有一点比较困惑的是当render loss 是0.7的时候我有打印出parameters ，vertices_rgb这部分一直是0貌似不受训练的影响，不知道是什么原因

**Comment by DRosemei** [comment]
@16Huzeyu 你可以尝试用eval里面的脚本，mesh render出来会有一个silhouette https://github.com/DRosemei/RoMe/blob/main/scripts/eval.py#L86 ，你可以检查下是否和原图对齐，如果mesh没有投影到图片上，silhouette也会把整张图mask掉，也就不参与学习

**Comment by rockywind** [comment]
@16Huzeyu @DRosemei 
您好，能提供自有数据如何跑maskformer，生成语义分割图的方法吗？repo里面的maskformer_infer脚本不能直接跑。

**Comment by 16Huzeyu** [comment]
@rockywind 主要改scripts/mask2former_infer/inference.py 里的 base dir 和savedir，然后配一下mask2former的环境就行，模型文件可以在mask2former的git上找到

**Comment by 16Huzeyu** [comment]
@rockywind @DRosemei  因为我的pose是用的nerfstudio的格式所以做了些逆变化之后可以成功一部分数据           pose =  
                    transform1 = np.array(
            [
                [0, -1, 0, 0],
                [0, 0, -1, 0],
                [1, 0, 0, 0],
                [0, 0, 0, 1],
            ]
        )
        transform2 = np.array(
            [
                [0, 0, 1, 0],
                [0, 1, 0, 0],
                [-1, 0, 0, 0],
                [0, 0, 0, 1],
            ]
        )

           np.linalg.inv(transform2) @ pose
            pose[2, :] *= -1
            pose = pose[np.array([1, 0, 2, 3]), :]
            pose[0:3, 1:3] *= -1
            pose = np.linalg.inv(transform1) @ pose
            然后设置高度self.camera_height = 2
![image](https://github.com/DRosemei/RoMe/assets/20391912/97a3e6b9-69da-449f-96ec-4c5d62fbba4e)

有几个问题
1.如图会把路沿上的树的范围也生成，是还有什么需要注意的点吗
2.输入数据是不是默认都是xy平面上采集的数据，所以z值基本固定。所以自定义数据集需要做一步旋转到xy平面的过程然后设置self.camera_height

**Comment by rockywind** [comment]
> @rockywind 主要改scripts/mask2former_infer/inference.py 里的 base dir 和savedir，然后配一下mask2former的环境就行，模型文件可以在mask2former的git上找到

您好，
我安装完maskformer,跑infer.sh,遇到这个问题。
````
(base) root@6hcnojmvo0f28-0:/rockywin.wang/NeRF/RoMe/scripts/mask2former_infer# bash infer.sh 
Traceback (most recent call last):
  File "inference.py", line 6, in <module>
    from predictor import VisualizationDemo
ModuleNotFoundError: No module named 'predictor'
````
infer.sh的脚本是这样的
````
export CUDA_VISIBLE_DEVICES=0
export PYTHONPATH="/rockywin.wang/NeRF/RoMe/Mask2Former"
python inference.py  --config-file /rockywin.wang/NeRF/RoMe/Mask2Former/configs/mapillary-vistas/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_300k.yaml \
 --opts MODEL.WEIGHTS /SHFP12/02_bevdet/SceneRF/01_thrd_data/model_final_90ee2d_map_seg.pkl
````
安装脚本是这个
````
# under your working directory
git clone git@github.com:facebookresearch/detectron2.git
cd detectron2
pip install -e .
pip install git+https://github.com/cocodataset/panopticapi.git
pip install git+https://github.com/mcordts/cityscapesScripts.git

cd ..
git clone git@github.com:facebookresearch/Mask2Former.git
cd Mask2Former
pip install -r requirements.txt
cd mask2former/modeling/pixel_decoder/ops
sh make.sh
````

**Comment by 16Huzeyu** [comment]
@rockywind 改成from demo.predictor import VisualizationDemo

**Comment by 16Huzeyu** [comment]
@rockywind 不知道你在使用自己的数据时，是怎么处理的，效果如何

**Comment by rockywind** [comment]
感谢感谢，我也是用nerfstudio的数据格式。
这是我的效果。
效果不好，应该是pose也有问题
![image](https://github.com/DRosemei/RoMe/assets/14838781/d36d596b-a077-40e5-9b4d-21bc8b450e94)

**Comment by 16Huzeyu** [comment]
transform1 = np.array(
[
[0, -1, 0, 0],
[0, 0, -1, 0],
[1, 0, 0, 0],
[0, 0, 0, 1],
]
)
transform2 = np.array(
[
[0, 0, 1, 0],
[0, 1, 0, 0],
[-1, 0, 0, 0],
[0, 0, 0, 1],
]
)

       np.linalg.inv(transform2) @ pose
        pose[2, :] *= -1
        pose = pose[np.array([1, 0, 2, 3]), :]
        pose[0:3, 1:3] *= -1
        pose = np.linalg.inv(transform1) @ pose

@rockywind 上面是我对pose的处理，你这边是怎么处理的，可以看一下吗

**Comment by rockywind** [comment]
> transform1 = np.array( [ [0, -1, 0, 0], [0, 0, -1, 0], [1, 0, 0, 0], [0, 0, 0, 1], ] ) transform2 = np.array( [ [0, 0, 1, 0], [0, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 0, 1], ] )
> 
> ```
>    np.linalg.inv(transform2) @ pose
>     pose[2, :] *= -1
>     pose = pose[np.array([1, 0, 2, 3]), :]
>     pose[0:3, 1:3] *= -1
>     pose = np.linalg.inv(transform1) @ pose
> ```
> 
> @rockywind 上面是我对pose的处理，你这边是怎么处理的，可以看一下吗

````
            Tr_cam_to_world_FrontRight = kitti_lidar_to_world @ Tr_cam_to_velo_FrontRight ````
我没有做opencv转opencl那一步。

**Comment by rockywind** [comment]
> @rockywind 改成from demo.predictor import VisualizationDemo
您好，我直接跑，会遇到这个问题。这是我的安装的环境问题。
````Traceback (most recent call last):
  File "inference.py", line 7, in <module>
    from demo.predictor import VisualizationDemo
  File "/rockywin.wang/NeRF/RoMe/Mask2Former/demo/predictor.py", line 14, in <module>
    from detectron2.modeling import build_model
  File "/rockywin.wang/NeRF/Mask2Former/detectron2/detectron2/modeling/__init__.py", line 20, in <module>
    from .meta_arch import (
  File "/rockywin.wang/NeRF/Mask2Former/detectron2/detectron2/modeling/meta_arch/__init__.py", line 6, in <module>
    from .panoptic_fpn import PanopticFPN
  File "/rockywin.wang/NeRF/Mask2Former/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py", line 14, in <module>
    from .rcnn import GeneralizedRCNN
  File "/rockywin.wang/NeRF/Mask2Former/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 12, in <module>
    from detectron2.utils.events import get_event_storage
  File "/rockywin.wang/NeRF/Mask2Former/detectron2/detectron2/utils/events.py", line 9, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/opt/conda/lib/python3.7/functools.py)````

**Comment by rockywind** [comment]
@16Huzeyu @DRosemei 
方便加个微信有什么方便讨论一下哈。
我的微信号：15394417826， 王晓权

**Comment by 16Huzeyu** [comment]
> @16Huzeyu @DRosemei 方便加个微信有什么方便讨论一下哈。 我的微信号：15394417826， 王晓权

已加

**Comment by 16Huzeyu** [comment]
> > transform1 = np.array( [ [0, -1, 0, 0], [0, 0, -1, 0], [1, 0, 0, 0], [0, 0, 0, 1], ] ) transform2 = np.array( [ [0, 0, 1, 0], [0, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 0, 1], ] )
> > ```
> >    np.linalg.inv(transform2) @ pose
> >     pose[2, :] *= -1
> >     pose = pose[np.array([1, 0, 2, 3]), :]
> >     pose[0:3, 1:3] *= -1
> >     pose = np.linalg.inv(transform1) @ pose
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @rockywind 上面是我对pose的处理，你这边是怎么处理的，可以看一下吗
> 
> `Tr_cam_to_world_FrontRight = kitti_lidar_to_world @ Tr_cam_to_velo_FrontRight` 我没有做opencv转opencl那一步。

所以你用的是kitii数据集？之前你提到的用的nerfstudio数据集的pose是怎么对象这个公式的几个元素的，nerfstudio的transforms.jsom应该就transform_matrix这个pose矩阵

**Comment by DRosemei** [comment]
> @rockywind @DRosemei 因为我的pose是用的nerfstudio的格式所以做了些逆变化之后可以成功一部分数据 pose = transform1 = np.array( [ [0, -1, 0, 0], [0, 0, -1, 0], [1, 0, 0, 0], [0, 0, 0, 1], ] ) transform2 = np.array( [ [0, 0, 1, 0], [0, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 0, 1], ] )
> 
> ```
>        np.linalg.inv(transform2) @ pose
>         pose[2, :] *= -1
>         pose = pose[np.array([1, 0, 2, 3]), :]
>         pose[0:3, 1:3] *= -1
>         pose = np.linalg.inv(transform1) @ pose
>         然后设置高度self.camera_height = 2
> ```
> 
> ![image](https://user-images.githubusercontent.com/20391912/256731954-97a3e6b9-69da-449f-96ec-4c5d62fbba4e.png)
> 
> 有几个问题 1.如图会把路沿上的树的范围也生成，是还有什么需要注意的点吗 2.输入数据是不是默认都是xy平面上采集的数据，所以z值基本固定。所以自定义数据集需要做一步旋转到xy平面的过程然后设置self.camera_height
@16Huzeyu 
问题1：可能是语义分割模型的问题，你可以检查下mask后的图片。
问题2：这里把位姿做了平面拟合，高度为相机高度，这样会更好优化高度
