### ISSUE TITLE
关于bev的深度的一些疑问

### ISSUE THREAD

**Issue by 16Huzeyu** [DRosemei/RoMe#8]
@DRosemei 你好，我这边注意到bev的深度被规范在0.8和1.2之间，这两个数字是怎么设计出来的，然后他们的单位是米吗还是具体什么含义？然后我看到有说
![image](https://github.com/DRosemei/RoMe/assets/20391912/0d842586-a05d-472a-a94c-38c5129dba60)
这个具体的原因是什么？

**Comment by DRosemei** [comment]
@16Huzeyu 这边只是可视化限制了范围，单位是米。因为仅靠光度损失和语义损失，很难恢复变化剧烈的高度，需要加入额外监督，比如lidar depth
