### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by yongguanjiangshan** [DRosemei/RoMe#9]
Hi, thank you for the great work! 
When i training, i get below problem.

> Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.

Do you know how to solve this? looking forward your reply! Thank you very much!

**Comment by DRosemei** [comment]
@yongguanjiangshan  Using pytorch3d==0.6.1 may solve it.

**Comment by yongguanjiangshan** [comment]
thank you for your reply! after install pytorch3d==0.6.1, problem solved!
